name: PR Quality Checks

on:
  pull_request:
    branches: [main]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install -r requirements-test.txt

      - name: Run linting
        run: |
          ruff check talisik/ tests/ api/
          black --check talisik/ tests/ api/

      - name: Run tests with coverage
        run: |
          pytest -v --cov=talisik --cov-report=term-missing

      - name: Test API functionality
        run: |
          python test_api.py &
          sleep 5  # Give API time to start
          # Add basic API health check here if needed
